# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-23 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220421_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 24, 2, 6, 2, 491840), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 24, 2, 6, 2, 492837), verbose_name='Дата комментария'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comments',
        ),
    ]
