# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-25 23:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220426_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 26, 2, 23, 30, 529122), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 26, 2, 23, 30, 529122), verbose_name='Дата комментария'),
        ),
    ]
